using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GuessTheNumber
{
    class Program
    {
        static void Main(string[] args)
        {
            // The code provided will print ‘Hello World’ to the console.
            // Press Ctrl+F5 (or go to Debug > Start Without Debugging) to run your app.
            Console.WriteLine("GUESS THE NUMBER");
            Console.WriteLine("by Sarah Herzog");
            Console.WriteLine("");
            Console.WriteLine("Guess a random number generated by the computer!");

            Random rand = new Random();
            int secretNumber = rand.Next(1, 10);
            Console.WriteLine("Our secret number is " + secretNumber);

            Console.WriteLine("Enter a number guess between 1 and 9:");
            int guess = Convert.ToInt32(Console.ReadLine());
            Console.WriteLine("You guessed " + guess);
            int numAttempts = 1;

            while (guess != secretNumber)
            {
                // keep guessing

                // Inform player they were wrong
                Console.WriteLine("Wrong! Try again!");
                if (secretNumber < guess)
                {
                    Console.WriteLine("The secret number is LESS than your guess " + guess);
                }
                else
                {
                    Console.WriteLine("The secret number is BIGGER than your guess " + guess);
                }

                // Read a new guess from the player
                Console.WriteLine("Guess another number between 1 and 9:");
                guess = Convert.ToInt32(Console.ReadLine());
                ++numAttempts;
            }

            // Now we have guessed the correct number
            Console.WriteLine("Correct! Well done!");
            Console.WriteLine("You guessed it in " + numAttempts + " attempts!");

            Console.ReadKey();

            // Go to http://aka.ms/dotnet-get-started-console to continue learning how to build a console app! 
        }
    }
}
